name: Test Prettier and Eslint Check
run-name: ${{ github.actor }} is running the format check
on:
  push:
    branches:
      - master
permissions:
  contents: read

jobs:
  do-the-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Put the App Folder into the executor virtual machine"
        uses: actions/checkout@v4

      - name: "Install Node.js"
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: "Install Dependencies"
        run: npm install

      - name: "Check if Prettier Formatted"
        id: prettier
        run: npm run format:check

      - name: "Check if Eslint Formatted"
        id: eslint
        if: ${{ success() && steps.prettier.conclusion == 'success' }}
        run: npm run lint

      - name: "Run Tests"
        id: jest
        if: ${{ success() && steps.eslint.conclusion == 'success' }}
        run: npm run test

      - name: "Conclusion"
        if: ${{ success() && steps.jest.conclusion == 'success' }}
        run: echo ✅ All Good !!!
